// ============================================
// DADOS DOS CHECKLISTS - NRs e Itens
// ============================================

const EQUIPMENT_TYPES = {
    maquinas: [
        {
            id: 'trator_esteira',
            name: 'Trator de Esteira',
            icon: '🚜',
            nr: 'NR-12',
            items: [
                { id: 'trator_esteira_doc', text: 'Documentação do equipamento em dia (CIR, seguro, licença)', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_treinamento', text: 'Operador com treinamento e qualificação (ASO validade)', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_extintor', text: 'Extintor de incêndio carregado, lacrado e dentro do prazo de validade', nr: 'NR-23', risk: 'high' },
                { id: 'trator_esteira_cinto', text: 'Cinto de segurança com trava-quedas', nr: 'NR-35', risk: 'high' },
                { id: 'trator_esteira_parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_bancos', text: 'Condições dos bancos, fixação e estofamento', nr: 'NR-12', risk: 'low' },
                { id: 'trator_esteira_retrovisores', text: 'Retrovisores interno e externos em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_escada', text: 'Escada de acesso à cabine em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_farol', text: 'Faróis funcionando (altas, baixas, lanternas)', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_sinal_sonoro', text: 'Sinal sonoro de ré funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_buzina', text: 'Buzina funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_faixa_refletiva', text: 'Faixa refletiva para visualização noturna', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_freio', text: 'Freio principal em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_freio_estacionamento', text: 'Freio de estacionamento funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_esteiras', text: 'Condição das esteiras (tensionamento, desgaste, links)', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_niveis', text: 'Níveis de óleo, água e combustível adequados', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_vazamentos', text: 'Ausência de vazamentos de óleo, combustível e água', nr: 'NR-12', risk: 'high' },
                { id: 'trator_esteira_rotacao', text: 'Rotação do motor e equipamento acima funcionando normalmente', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_alarmes', text: 'Alarmes e indicadores do painel funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_esteira_limpeza', text: 'Equipamento limpo e organizado', nr: 'NR-12', risk: 'low' },
                { id: 'trator_esteira_placa_identificacao', text: 'Placa de identificação e capacidade de carga visível', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'trator_agricola',
            name: 'Trator Agrícola',
            icon: '🌾',
            nr: 'NR-12',
            items: [
                { id: 'trator_agricola_doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'trator_agricola_cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'trator_agricola_ROPS', text: 'Dispositivo de proteção contra capotagem (ROPS)', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_agricola_retrovisores', text: 'Retrovisores em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_agricola_farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_agricola_freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_niveis', text: 'Níveis de óleo, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_agricola_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_pneus', text: 'Condição dos pneus e calibragem', nr: 'NR-12', risk: 'medium' },
                { id: 'trator_agricola_acoplamento', text: 'Sistema de acoplamento de implementos', nr: 'NR-12', risk: 'high' },
                { id: 'trator_agricola_PTO', text: 'Eixo de potência (PTO) com proteção', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'escavadeira',
            name: 'Escavadeira Hidráulica',
            icon: '⛏️',
            nr: 'NR-12',
            items: [
                { id: 'escavadeira_doc', text: 'Documentação do equipamento em dia (CIR, seguro)', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'escavadeira_cinto', text: 'Cinto de segurança com trava-quedas', nr: 'NR-35', risk: 'high' },
                { id: 'escavadeira_parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'escavadeira_bancos', text: 'Condições dos bancos e fixação', nr: 'NR-12', risk: 'low' },
                { id: 'escavadeira_retrovisores', text: 'Retrovisores interno e externos', nr: 'NR-12', risk: 'medium' },
                { id: 'escavadeira_escada', text: 'Escada e corrimãos de acesso', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_farol', text: 'Faróis e lanternas funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'escavadeira_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_freio_estacionamento', text: 'Freio de estacionamento', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_niveis', text: 'Níveis de óleo hidráulico, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'escavadeira_vazamentos', text: 'Ausência de vazamentos hidráulicos', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_bracos', text: 'Condição dos braços e cilindros hidráulicos', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_labor', text: 'Condição da lâmina/balde', nr: 'NR-12', risk: 'medium' },
                { id: 'escavadeira_cabo', text: 'Cabos de aço em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_limitador', text: 'Limitador de carga instalado e funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'escavadeira_alarmes', text: 'Alarmes e indicadores do painel', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'retroescavadeira',
            name: 'Retroescavadeira',
            icon: '🏗️',
            nr: 'NR-12',
            items: [
                { id: 'retroescavadeira_doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'retroescavadeira_cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'retroescavadeira_ROPS', text: 'Dispositivo de proteção contra capotagem (ROPS)', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_farol', text: 'Faróis e lanternas', nr: 'NR-12', risk: 'medium' },
                { id: 'retroescavadeira_freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_niveis', text: 'Níveis de óleo, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'retroescavadeira_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_hidraulico', text: 'Sistema hidráulico em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'retroescavadeira_pneus', text: 'Condição dos pneus', nr: 'NR-12', risk: 'medium' },
                { id: 'retroescavadeira_pá', text: 'Condição da pá (dentes, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'retroescavadeira_garfo', text: 'Condição do garfo (se aplicável)', nr: 'NR-12', risk: 'medium' },
                { id: 'retroescavadeira_alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'rolo',
            name: 'Rolo Compactador',
            icon: '⚙️',
            nr: 'NR-12',
            items: [
                { id: 'rolo_doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'rolo_treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'rolo_extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'rolo_cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'rolo_ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'rolo_freio', text: 'Freios funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'rolo_vibracao', text: 'Sistema de vibração funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'rolo_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'rolo_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'rolo_rolos', text: 'Condição dos rolos (superfície, bordas)', nr: 'NR-12', risk: 'medium' },
                { id: 'rolo_alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'gerador',
            name: 'Gerador',
            icon: '⚡',
            nr: 'NR-10',
            items: [
                { id: 'gerador_doc', text: 'Documentação do equipamento em dia', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_treinamento', text: 'Operador qualificado para operação', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_aterramento', text: 'Sistema de aterramento elétrico aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_disjuntor', text: 'Disjuntor geral funcionando', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_cabinado', text: 'Parte elétrica cabineada e trancada', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'gerador_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-10', risk: 'medium' },
                { id: 'gerador_vazamentos', text: 'Ausência de vazamentos de combustível', nr: 'NR-10', risk: 'high' },
                { id: 'gerador_ventilacao', text: 'Ventilação e resfriamento adequados', nr: 'NR-10', risk: 'medium' },
                { id: 'gerador_ruidos', text: 'Nível de ruído dentro da normalidade', nr: 'NR-10', risk: 'low' },
                { id: 'gerador_placa', text: 'Placa de identificação e dados técnicos visível', nr: 'NR-10', risk: 'medium' },
                { id: 'gerador_cabeamento', text: 'Cabeamento elétrico em bom estado', nr: 'NR-10', risk: 'high' },
            ]
        },
        {
            id: 'betoneira',
            name: 'Betoneira Elétrica',
            icon: '🪣',
            nr: 'NR-12',
            items: [
                { id: 'betoneira_doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'betoneira_treinamento', text: 'Operador treinado', nr: 'NR-12', risk: 'high' },
                { id: 'betoneira_aterramento', text: 'Cabeamento de terra aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'betoneira_cabo', text: 'Cabo de alimentação em bom estado', nr: 'NR-10', risk: 'high' },
                { id: 'betoneira_extintor', text: 'Extintor de incêndio próximo', nr: 'NR-23', risk: 'high' },
                { id: 'betoneira_tambor', text: 'Tambor limpo e em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'betoneira_pá', text: 'Pá de amassar em bom estado', nr: 'NR-12', risk: 'low' },
                { id: 'betoneira_rolamento', text: 'Rolamentos e engrenagens protegidos', nr: 'NR-12', risk: 'high' },
                { id: 'betoneira_tela', text: 'Tela de proteção instalada', nr: 'NR-12', risk: 'high' },
                { id: 'betoneira_chassi', text: 'Chassi e estrutura sem fissuras', nr: 'NR-12', risk: 'medium' },
                { id: 'betoneira_interrupcao', text: 'Dispositivo de emergência funcionando', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'embarcacao',
            name: 'Embarcação',
            icon: '🚢',
            nr: 'NR-30',
            items: [
                { id: 'embarcacao_doc', text: 'Documentação da embarcação em dia', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_tripulacao', text: 'Tripulação qualificada e documentada', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_coletes', text: 'Coletes salva-vidas para todos os ocupantes', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_extintor', text: 'Extintores de incêndio válidos', nr: 'NR-23', risk: 'high' },
                { id: 'embarcacao_botes', text: 'Botes salva-vidas em bom estado', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_sinalizacao', text: 'Sinalização de socorro (rádio, fogos)', nr: 'NR-30', risk: 'medium' },
                { id: 'embarcacao_motor', text: 'Motor em perfeitas condições', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_combustivel', text: 'Nível de combustível adequado', nr: 'NR-30', risk: 'medium' },
                { id: 'embarcacao_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_casco', text: 'Condição do casco (sem fissuras, sem vazamentos)', nr: 'NR-30', risk: 'high' },
                { id: 'embarcacao_equipamentos', text: 'Equipamentos de navegação funcionando', nr: 'NR-30', risk: 'medium' },
                { id: 'embarcacao_limpeza', text: 'Embarcação limpa e organizada', nr: 'NR-30', risk: 'low' },
            ]
        },
        {
            id: 'minicarregadeira',
            name: 'Minicarregadeira',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'minicarregadeira_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'minicarregadeira_treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'minicarregadeira_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'minicarregadeira_freio', text: 'Freios funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'minicarregadeira_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'minicarregadeira_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'minicarregadeira_garfo', text: 'Condição dos garfos', nr: 'NR-12', risk: 'medium' },
                { id: 'minicarregadeira_estabilidade', text: 'Sistema de estabilidade aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'minicarregadeira_alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'bomba',
            name: 'Bomba Estacionária',
            icon: '💧',
            nr: 'NR-12',
            items: [
                { id: 'bomba_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'bomba_treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'bomba_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'bomba_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'bomba_tubulacoes', text: 'Tubulações e conexões em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'bomba_valvulas', text: 'Válvulas funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'bomba_mancal', text: 'Mancal e selagem em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'bomba_vibracao', text: 'Nível de vibração dentro da normalidade', nr: 'NR-12', risk: 'medium' },
                { id: 'bomba_ruidos', text: 'Nível de ruído normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'motoniveladora',
            name: 'Motoniveladora',
            icon: '🚜',
            nr: 'NR-12',
            items: [
                { id: 'motoniveladora_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'motoniveladora_cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'motoniveladora_ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'motoniveladora_freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'motoniveladora_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_lamina', text: 'Condição da lâmina (garras, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'motoniveladora_articulacao', text: 'Articulação da lâmina aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'motoniveladora_alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'pcarregadeira',
            name: 'Pá Carregadeira',
            icon: '🚛',
            nr: 'NR-12',
            items: [
                { id: 'pcarregadeira_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'pcarregadeira_treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'pcarregadeira_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'pcarregadeira_cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'pcarregadeira_ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'pcarregadeira_farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'pcarregadeira_freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'pcarregadeira_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'pcarregadeira_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'pcarregadeira_balde', text: 'Condição do balde (dentes, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'pcarregadeira_suspencao', text: 'Suspensão em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'pcarregadeira_alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'plataforma',
            name: 'Plataforma Elevatória',
            icon: '🪜',
            nr: 'NR-12',
            items: [
                { id: 'plataforma_doc', text: 'Documentação em dia (CIR, seguro)', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_treinamento', text: 'Operador qualificado e certificado', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'plataforma_cinto', text: 'Trava-quedas e cinto para todos os ocupantes', nr: 'NR-35', risk: 'high' },
                { id: 'plataforma_plataforma', text: 'Plataforma de trabalho íntegra', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_guarda_corpo', text: 'Guarda-corpo e rodapé instalados', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_escada', text: 'Escada de acesso aprovado', nr: 'NR-12', risk: 'medium' },
                { id: 'plataforma_hidraulico', text: 'Sistema hidráulico sem vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_freio', text: 'Freios e trava funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_niveis', text: 'Níveis hidráulicos', nr: 'NR-12', risk: 'medium' },
                { id: 'plataforma_limitador', text: 'Limitador de carga e altura aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'plataforma_alarmes', text: 'Alarmes de inclinação e carga', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'sondagem',
            name: 'Equipamento de Sondagem',
            icon: '🔩',
            nr: 'NR-12',
            items: [
                { id: 'sondagem_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'sondagem_estabilidade', text: 'Sistema de estabilidade aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_torre', text: 'Torre de sondagem íntegra', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_cabo', text: 'Cabos de aço em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_freio', text: 'Freios de emergência funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'sondagem_vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'sondagem_protecao', text: 'Proteções e guarda-corpos instalados', nr: 'NR-12', risk: 'high' },
            ]
        },
    ],
    veiculos: [
        {
            id: 'veiculos_leves',
            name: 'Veículos Leves',
            icon: '🚗',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'veiculos_leves_interdicao', text: 'Ausência de vazamento de óleo', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_vazamento_agua', text: 'Ausência de vazamento de água', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_cinto', text: 'Cinto de segurança funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_doc_ipva', text: 'Documentação em dia (IPVA, licenciamento)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_extintor', text: 'Extintor de incêndio carregado, lacrado e dentro do prazo', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_freio_estac', text: 'Freio de estacionamento funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_freio_pe', text: 'Freios de pé em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_habilitacao', text: 'Habilitação do condutor em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_luzes', text: 'Luzes funcionando (farol, ré, setas, freio, interna, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_triangulo', text: 'Triângulo / Macaco / Chave de roda', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_velocimetro', text: 'Velocímetro / marcador de combustível / temperatura funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_pneus', text: 'Pneus / estepe / parafusos das rodas em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'veiculos_leves_ar', text: 'Ar condicionado funcionando', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_parabrisa', text: 'Condições do para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_retrovisor', text: 'Condições do retrovisor interno e externo', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_bancos', text: 'Condições dos bancos / fixação / estofamento', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_fechadura', text: 'Fechadura / Maçanetas / Trancas em geral', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_limpador', text: 'Limpador em funcionamento / palhetas em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_ruido_interno', text: 'Nível de ruído interno dentro da normalidade', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_ruido_externo', text: 'Nível de ruído externo dentro da normalidade', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_painel', text: 'Indicações de anomalia no painel (injeção, óleo, airbag...)', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_quebra_sol', text: 'Quebra-sol', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_vidro', text: 'Vidro elétrico / Travas', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'veiculos_leves_suspencao', text: 'Suspensão / alinhamento / balanceamento', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'van',
            name: 'Van',
            icon: '🚐',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'van_interdicao', text: 'Ausência de vazamento de óleo', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_cinto', text: 'Cinto de segurança para todos os ocupantes', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_capacidade', text: 'Respeitar capacidade de passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'van_buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'van_retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'van_bancos', text: 'Bancos em bom estado', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'van_limpador', text: 'Limpador de para-brisa funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'van_painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'van_bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'ambulancia',
            name: 'Ambulância',
            icon: '🚑',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'ambulancia_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_luzes', text: 'Luzes funcionando (farol, seta, emergência)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_cinto', text: 'Cintos de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_equipamentos', text: 'Equipamentos de socorro em ordem', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_oxigenio', text: 'Cilindro de oxigênio cheio e válido', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ambulancia_maca', text: 'Macá em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ambulancia_buzina', text: 'Buzina e sirene funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ambulancia_retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ambulancia_limpador', text: 'Limpador funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ambulancia_painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'ambulancia_bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'onibus',
            name: 'Ônibus',
            icon: '🚌',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'onibus_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_habilitacao', text: 'Habilitação do condutor (categoria D/E)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_extintor', text: 'Extintores válidos (quantidade adequada)', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_cintos', text: 'Cintos de segurança para todos os assentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_saidas', text: 'Saídas de emergência desobstruídas', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_macanetas', text: 'Maçanetas de emergência funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_capacidade', text: 'Respeitar capacidade máxima de passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'onibus_buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'onibus_retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'onibus_limpador', text: 'Limpador de para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'onibus_ar', text: 'Ar condicionado / ventilação', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'onibus_bancos', text: 'Bancos em bom estado', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'onibus_painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_cabinado',
            name: 'Caminhão Cabinado',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'caminhao_cabinado_doc', text: 'Documentação em dia (CIV, seguro, RNTRC)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_habilitacao', text: 'Habilitação do condutor (categoria E)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_freio_motor', text: 'Freio motor funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_luzes', text: 'Luzes funcionando (farol, ré, setas, freio, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_pneus', text: 'Pneus / estepe em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_triangulo', text: 'Triângulo / Macaco / Chave de roda', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_vazamento', text: 'Ausência de vazamentos (óleo, ar, combustível)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_ar_comprimido', text: 'Sistema de ar comprimido aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_reboque', text: 'Acoplamento reboque aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_cabinado_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_limpador', text: 'Limpador de para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_bancos', text: 'Bancos / estofamento', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'caminhao_cabinado_suspencao', text: 'Suspensão em geral', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_munk',
            name: 'Caminhão Munk',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'caminhao_munk_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_munk', text: 'Sistema Munk (guindaste) aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_estabilizador', text: 'Estabilizadores aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_cabo', text: 'Cabos de aço em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_munk_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_munk_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_munk_retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_munk_painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_comboio',
            name: 'Caminhão Comboio',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'caminhao_comboio_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_capacidade', text: 'Respeitar capacidade de carga/passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_comboio_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_comboio_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_comboio_retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_comboio_painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_pipa',
            name: 'Caminhão Pipa',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'caminhao_pipa_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_tanque', text: 'Tanque / reservatório aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_valvulas', text: 'Válvulas e registros funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'caminhao_pipa_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_pipa_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_pipa_retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_pipa_painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_basculante',
            name: 'Caminhão Basculante',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'caminhao_basculante_doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_basculamento', text: 'Sistema de basculamento aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_caçamba', text: 'Caçamba em bom estado (sem fissuras)', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_cilindro', text: 'Cilindro hidráulico aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caminhao_basculante_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_basculante_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_basculante_retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'caminhao_basculante_painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'carreta',
            name: 'Carreta',
            icon: '🚚',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'carreta_doc', text: 'Documentação em dia (CIV, RNTRC)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_freio', text: 'Freios da carreta funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_acoplamento', text: 'Acoplamento (trilho, quinta roda) aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_luzes', text: 'Luzes funcionando (setas, freio, ré, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_vazamento', text: 'Ausência de vazamentos (ar, óleo)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_ar_comprimido', text: 'Sistema de ar comprimido aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_capacidade', text: 'Respeitar capacidade de carga', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'carreta_tampa', text: 'Tampas laterais / lonas aprovado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'carreta_sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'carreta_buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'carreta_retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'carreta_suspensao', text: 'Suspensão em geral', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
    ],
    ferramentas: [
        {
            id: 'serra_tico',
            name: 'Serra Tico-Tico',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'serra_tico_doc', text: 'Documentação da ferramenta em dia', nr: 'NR-12', risk: 'high' },
                { id: 'serra_tico_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'serra_tico_cabo', text: 'Cabo de alimentação em bom estado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_tico_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_tico_lamine', text: 'Lâmina em bom estado e adequada', nr: 'NR-12', risk: 'medium' },
                { id: 'serra_tico_protecao', text: 'Proteção de lâmina instalada', nr: 'NR-12', risk: 'high' },
                { id: 'serra_tico_interruptor', text: 'Interruptor de emergência funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'serra_tico_carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
                { id: 'serra_tico_vibracao', text: 'Nível de vibração normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'serra_circular_bancada',
            name: 'Serra Circular de Bancada',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'serra_circular_bancada_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_bancada_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_bancada_cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_circular_bancada_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_circular_bancada_lamine', text: 'Lâmina em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'serra_circular_bancada_protecao', text: 'Proteção de lâmina e guia paralela', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_bancada_mesa', text: 'Mesa de apoio em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'serra_circular_bancada_extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'serra_circular_bancada_limpeza', text: 'Área de trabalho limpa e sem obstáculos', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'serra_circular_portatil',
            name: 'Serra Circular Portátil',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'serra_circular_portatil_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_portatil_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_portatil_cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_circular_portatil_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'serra_circular_portatil_lamine', text: 'Lâmina em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'serra_circular_portatil_protecao', text: 'Proteção de lâmina', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_portatil_interruptor', text: 'Interruptor de emergência', nr: 'NR-12', risk: 'high' },
                { id: 'serra_circular_portatil_carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'lixadeira',
            name: 'Lixadeira Elétrica',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'lixadeira_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'lixadeira_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'lixadeira_cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'lixadeira_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'lixadeira_disco', text: 'Disco/lixa em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'lixadeira_protecao', text: 'Proteção (tela) instalada', nr: 'NR-12', risk: 'high' },
                { id: 'lixadeira_mascara', text: 'Máscara/palheta disponível', nr: 'NR-6', risk: 'high' },
                { id: 'lixadeira_carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'furadeira',
            name: 'Furadeira Elétrica',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'furadeira_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'furadeira_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'furadeira_cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'furadeira_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'furadeira_broca', text: 'Broca em bom estado e fixada', nr: 'NR-12', risk: 'medium' },
                { id: 'furadeira_mandril', text: 'Mandril funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'furadeira_carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
                { id: 'furadeira_interruptor', text: 'Interruptor funcionando', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'compressor',
            name: 'Compressor de Ar',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'compressor_doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'compressor_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'compressor_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'compressor_vazamento', text: 'Ausência de vazamentos de ar', nr: 'NR-12', risk: 'high' },
                { id: 'compressor_válvula', text: 'Válvula de segurança funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'compressor_manometro', text: 'Manômetro funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'compressor_niveis', text: 'Níveis de óleo e filtros', nr: 'NR-12', risk: 'medium' },
                { id: 'compressor_correia', text: 'Correias em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'compressor_extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'compressor_ruidos', text: 'Nível de ruído normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'solda',
            name: 'Máquina de Solda',
            icon: '🔧',
            nr: 'NR-10',
            items: [
                { id: 'solda_doc', text: 'Documentação em dia', nr: 'NR-10', risk: 'high' },
                { id: 'solda_treinamento', text: 'Usuário qualificado (NR-10)', nr: 'NR-10', risk: 'high' },
                { id: 'solda_aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'solda_cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'solda_eletrodos', text: 'Eletrodos/Arames adequados', nr: 'NR-10', risk: 'medium' },
                { id: 'solda_mascara', text: 'Máscara de solda em bom estado', nr: 'NR-6', risk: 'high' },
                { id: 'solda_luvas', text: 'Luvas de vaqueta', nr: 'NR-6', risk: 'high' },
                { id: 'solda_extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'solda_ventilacao', text: 'Ventilação adequada no local', nr: 'NR-15', risk: 'high' },
                { id: 'solda_fogos', text: 'Ausência de materiais inflamáveis próximos', nr: 'NR-23', risk: 'high' },
            ]
        },
        {
            id: 'guindacho',
            name: 'Acessório de Guindacho',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'guindacho_doc', text: 'Documentação em dia (certificado de qualidade)', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_correntes', text: 'Correntes em bom estado (sem trincas, desgaste)', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_ganchos', text: 'Ganchos com trava de segurança', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_alcatra', text: 'Alcatra em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_capacidade', text: 'Capacidade de carga identificada', nr: 'NR-12', risk: 'high' },
                { id: 'guindacho_inspecao', text: 'Inspeção periódica em dia', nr: 'NR-12', risk: 'high' },
            ]
        },
    ]
};

// Mapeamento de IDs para nomes amigáveis
const ITEM_NAMES = {
    'trator_esteira_doc': 'Documentação do equipamento em dia (CIR, seguro, licença)',
    'trator_esteira_treinamento': 'Operador com treinamento e qualificação (ASO validade)',
    'trator_esteira_extintor': 'Extintor de incêndio carregado, lacrado e dentro do prazo de validade',
    'trator_esteira_cinto': 'Cinto de segurança com trava-quedas',
    'trator_esteira_parabrisa': 'Condições do para-brisa e limpador',
    'trator_esteira_bancos': 'Condições dos bancos, fixação e estofamento',
    'trator_esteira_retrovisores': 'Retrovisores interno e externos em bom estado',
    'trator_esteira_escada': 'Escada de acesso à cabine em bom estado',
    'trator_esteira_farol': 'Faróis funcionando (altas, baixas, lanternas)',
    'trator_esteira_sinal_sonoro': 'Sinal sonoro de ré funcionando',
    'trator_esteira_buzina': 'Buzina funcionando',
    'trator_esteira_faixa_refletiva': 'Faixa refletiva para visualização noturna',
    'trator_esteira_freio': 'Freio principal em perfeitas condições',
    'trator_esteira_freio_estacionamento': 'Freio de estacionamento funcionando',
    'trator_esteira_esteiras': 'Condição das esteiras (tensionamento, desgaste, links)',
    'trator_esteira_niveis': 'Níveis de óleo, água e combustível adequados',
    'trator_esteira_vazamentos': 'Ausência de vazamentos de óleo, combustível e água',
    'trator_esteira_rotacao': 'Rotação do motor e equipamento acima funcionando normalmente',
    'trator_esteira_alarmes': 'Alarmes e indicadores do painel funcionando',
    'trator_esteira_limpeza': 'Equipamento limpo e organizado',
    'trator_esteira_placa_identificacao': 'Placa de identificação e capacidade de carga visível',
    'trator_agricola_doc': 'Documentação do equipamento em dia',
    'trator_agricola_treinamento': 'Operador com treinamento e qualificação',
    'trator_agricola_extintor': 'Extintor de incêndio válido',
    'trator_agricola_cinto': 'Cinto de segurança',
    'trator_agricola_ROPS': 'Dispositivo de proteção contra capotagem (ROPS)',
    'trator_agricola_parabrisa': 'Condições do para-brisa e limpador',
    'trator_agricola_retrovisores': 'Retrovisores em bom estado',
    'trator_agricola_farol': 'Faróis funcionando',
    'trator_agricola_freio': 'Freios em perfeitas condições',
    'trator_agricola_niveis': 'Níveis de óleo, água e combustível',
    'trator_agricola_vazamentos': 'Ausência de vazamentos',
    'trator_agricola_pneus': 'Condição dos pneus e calibragem',
    'trator_agricola_acoplamento': 'Sistema de acoplamento de implementos',
    'trator_agricola_PTO': 'Eixo de potência (PTO) com proteção',
    'escavadeira_doc': 'Documentação do equipamento em dia (CIR, seguro)',
    'escavadeira_treinamento': 'Operador com treinamento e qualificação',
    'escavadeira_extintor': 'Extintor de incêndio válido',
    'escavadeira_cinto': 'Cinto de segurança com trava-quedas',
    'escavadeira_parabrisa': 'Condições do para-brisa e limpador',
    'escavadeira_bancos': 'Condições dos bancos e fixação',
    'escavadeira_retrovisores': 'Retrovisores interno e externos',
    'escavadeira_escada': 'Escada e corrimãos de acesso',
    'escavadeira_farol': 'Faróis e lanternas funcionando',
    'escavadeira_sinal_sonoro': 'Sinal sonoro de ré',
    'escavadeira_freio': 'Freios em perfeitas condições',
    'escavadeira_freio_estacionamento': 'Freio de estacionamento',
    'escavadeira_niveis': 'Níveis de óleo hidráulico, água e combustível',
    'escavadeira_vazamentos': 'Ausência de vazamentos hidráulicos',
    'escavadeira_bracos': 'Condição dos braços e cilindros hidráulicos',
    'escavadeira_labor': 'Condição da lâmina/balde',
    'escavadeira_cabo': 'Cabos de aço em bom estado',
    'escavadeira_limitador': 'Limitador de carga instalado e funcionando',
    'escavadeira_alarmes': 'Alarmes e indicadores do painel',
    'retroescavadeira_doc': 'Documentação do equipamento em dia',
    'retroescavadeira_treinamento': 'Operador com treinamento e qualificação',
    'retroescavadeira_extintor': 'Extintor de incêndio válido',
    'retroescavadeira_cinto': 'Cinto de segurança',
    'retroescavadeira_ROPS': 'Dispositivo de proteção contra capotagem (ROPS)',
    'retroescavadeira_farol': 'Faróis e lanternas',
    'retroescavadeira_freio': 'Freios em perfeitas condições',
    'retroescavadeira_niveis': 'Níveis de óleo, água e combustível',
    'retroescavadeira_vazamentos': 'Ausência de vazamentos',
    'retroescavadeira_hidraulico': 'Sistema hidráulico em bom estado',
    'retroescavadeira_pneus': 'Condição dos pneus',
    'retroescavadeira_pá': 'Condição da pá (dentes, lâmina)',
    'retroescavadeira_garfo': 'Condição do garfo (se aplicável)',
    'retroescavadeira_alarmes': 'Alarmes e indicadores',
    'rolo_doc': 'Documentação do equipamento em dia',
    'rolo_treinamento': 'Operador com treinamento e qualificação',
    'rolo_extintor': 'Extintor de incêndio válido',
    'rolo_cinto': 'Cinto de segurança',
    'rolo_ROPS': 'ROPS/FOPS instalado',
    'rolo_freio': 'Freios funcionando',
    'rolo_vibracao': 'Sistema de vibração funcionando',
    'rolo_niveis': 'Níveis de óleo e combustível',
    'rolo_vazamentos': 'Ausência de vazamentos',
    'rolo_rolos': 'Condição dos rolos (superfície, bordas)',
    'rolo_alarmes': 'Alarmes e indicadores',
    'gerador_doc': 'Documentação do equipamento em dia',
    'gerador_treinamento': 'Operador qualificado para operação',
    'gerador_aterramento': 'Sistema de aterramento elétrico aprovado',
    'gerador_disjuntor': 'Disjuntor geral funcionando',
    'gerador_cabinado': 'Parte elétrica cabineada e trancada',
    'gerador_extintor': 'Extintor de incêndio válido',
    'gerador_niveis': 'Níveis de óleo e combustível',
    'gerador_vazamentos': 'Ausência de vazamentos de combustível',
    'gerador_ventilacao': 'Ventilação e resfriamento adequados',
    'gerador_ruidos': 'Nível de ruído dentro da normalidade',
    'gerador_placa': 'Placa de identificação e dados técnicos visível',
    'gerador_cabeamento': 'Cabeamento elétrico em bom estado',
    'betoneira_doc': 'Documentação do equipamento em dia',
    'betoneira_treinamento': 'Operador treinado',
    'betoneira_aterramento': 'Cabeamento de terra aprovado',
    'betoneira_cabo': 'Cabo de alimentação em bom estado',
    'betoneira_extintor': 'Extintor de incêndio próximo',
    'betoneira_tambor': 'Tambor limpo e em bom estado',
    'betoneira_pá': 'Pá de amassar em bom estado',
    'betoneira_rolamento': 'Rolamentos e engrenagens protegidos',
    'betoneira_tela': 'Tela de proteção instalada',
    'betoneira_chassi': 'Chassi e estrutura sem fissuras',
    'betoneira_interrupcao': 'Dispositivo de emergência funcionando',
    'embarcacao_doc': 'Documentação da embarcação em dia',
    'embarcacao_tripulacao': 'Tripulação qualificada e documentada',
    'embarcacao_coletes': 'Coletes salva-vidas para todos os ocupantes',
    'embarcacao_extintor': 'Extintores de incêndio válidos',
    'embarcacao_botes': 'Botes salva-vidas em bom estado',
    'embarcacao_sinalizacao': 'Sinalização de socorro (rádio, fogos)',
    'embarcacao_motor': 'Motor em perfeitas condições',
    'embarcacao_combustivel': 'Nível de combustível adequado',
    'embarcacao_vazamentos': 'Ausência de vazamentos',
    'embarcacao_casco': 'Condição do casco (sem fissuras, sem vazamentos)',
    'embarcacao_equipamentos': 'Equipamentos de navegação funcionando',
    'embarcacao_limpeza': 'Embarcação limpa e organizada',
    'minicarregadeira_doc': 'Documentação em dia',
    'minicarregadeira_treinamento': 'Operador qualificado',
    'minicarregadeira_extintor': 'Extintor válido',
    'minicarregadeira_freio': 'Freios funcionando',
    'minicarregadeira_niveis': 'Níveis de óleo e combustível',
    'minicarregadeira_vazamentos': 'Ausência de vazamentos',
    'minicarregadeira_garfo': 'Condição dos garfos',
    'minicarregadeira_estabilidade': 'Sistema de estabilidade aprovado',
    'minicarregadeira_alarmes': 'Alarmes e indicadores',
    'bomba_doc': 'Documentação em dia',
    'bomba_treinamento': 'Operador qualificado',
    'bomba_aterramento': 'Aterramento aprovado',
    'bomba_vazamentos': 'Ausência de vazamentos',
    'bomba_tubulacoes': 'Tubulações e conexões em bom estado',
    'bomba_valvulas': 'Válvulas funcionando',
    'bomba_mancal': 'Mancal e selagem em bom estado',
    'bomba_vibracao': 'Nível de vibração dentro da normalidade',
    'bomba_ruidos': 'Nível de ruído normal',
    'motoniveladora_doc': 'Documentação em dia',
    'motoniveladora_treinamento': 'Operador qualificado',
    'motoniveladora_extintor': 'Extintor válido',
    'motoniveladora_cinto': 'Cinto de segurança',
    'motoniveladora_ROPS': 'ROPS/FOPS instalado',
    'motoniveladora_farol': 'Faróis funcionando',
    'motoniveladora_freio': 'Freios em perfeitas condições',
    'motoniveladora_niveis': 'Níveis de óleo e combustível',
    'motoniveladora_vazamentos': 'Ausência de vazamentos',
    'motoniveladora_lamina': 'Condição da lâmina (garras, lâmina)',
    'motoniveladora_articulacao': 'Articulação da lâmina aprovado',
    'motoniveladora_alarmes': 'Alarmes e indicadores',
    'pcarregadeira_doc': 'Documentação em dia',
    'pcarregadeira_treinamento': 'Operador qualificado',
    'pcarregadeira_extintor': 'Extintor válido',
    'pcarregadeira_cinto': 'Cinto de segurança',
    'pcarregadeira_ROPS': 'ROPS/FOPS instalado',
    'pcarregadeira_farol': 'Faróis funcionando',
    'pcarregadeira_freio': 'Freios em perfeitas condições',
    'pcarregadeira_niveis': 'Níveis de óleo e combustível',
    'pcarregadeira_vazamentos': 'Ausência de vazamentos',
    'pcarregadeira_balde': 'Condição do balde (dentes, lâmina)',
    'pcarregadeira_suspencao': 'Suspensão em bom estado',
    'pcarregadeira_alarmes': 'Alarmes e indicadores',
    'plataforma_doc': 'Documentação em dia (CIR, seguro)',
    'plataforma_treinamento': 'Operador qualificado e certificado',
    'plataforma_extintor': 'Extintor válido',
    'plataforma_cinto': 'Trava-quedas e cinto para todos os ocupantes',
    'plataforma_plataforma': 'Plataforma de trabalho íntegra',
    'plataforma_guarda_corpo': 'Guarda-corpo e rodapé instalados',
    'plataforma_escada': 'Escada de acesso aprovado',
    'plataforma_hidraulico': 'Sistema hidráulico sem vazamentos',
    'plataforma_freio': 'Freios e trava funcionando',
    'plataforma_niveis': 'Níveis hidráulicos',
    'plataforma_limitador': 'Limitador de carga e altura aprovado',
    'plataforma_alarmes': 'Alarmes de inclinação e carga',
    'sondagem_doc': 'Documentação em dia',
    'sondagem_treinamento': 'Operador qualificado',
    'sondagem_extintor': 'Extintor válido',
    'sondagem_estabilidade': 'Sistema de estabilidade aprovado',
    'sondagem_torre': 'Torre de sondagem íntegra',
    'sondagem_cabo': 'Cabos de aço em bom estado',
    'sondagem_freio': 'Freios de emergência funcionando',
    'sondagem_niveis': 'Níveis de óleo e combustível',
    'sondagem_vazamentos': 'Ausência de vazamentos',
    'sondagem_protecao': 'Proteções e guarda-corpos instalados',
    'veiculos_leves_interdicao': 'Ausência de vazamento de óleo',
    'veiculos_leves_vazamento_agua': 'Ausência de vazamento de água',
    'veiculos_leves_cinto': 'Cinto de segurança funcionando',
    'veiculos_leves_doc_ipva': 'Documentação em dia (IPVA, licenciamento)',
    'veiculos_leves_extintor': 'Extintor de incêndio carregado, lacrado e dentro do prazo',
    'veiculos_leves_freio_estac': 'Freio de estacionamento funcionando',
    'veiculos_leves_freio_pe': 'Freios de pé em perfeitas condições',
    'veiculos_leves_habilitacao': 'Habilitação do condutor em dia',
    'veiculos_leves_luzes': 'Luzes funcionando (farol, ré, setas, freio, interna, placa)',
    'veiculos_leves_triangulo': 'Triângulo / Macaco / Chave de roda',
    'veiculos_leves_velocimetro': 'Velocímetro / marcador de combustível / temperatura funcionando',
    'veiculos_leves_pneus': 'Pneus / estepe / parafusos das rodas em bom estado',
    'veiculos_leves_ar': 'Ar condicionado funcionando',
    'veiculos_leves_buzina': 'Buzina funcionando',
    'veiculos_leves_parabrisa': 'Condições do para-brisa',
    'veiculos_leves_retrovisor': 'Condições do retrovisor interno e externo',
    'veiculos_leves_bancos': 'Condições dos bancos / fixação / estofamento',
    'veiculos_leves_fechadura': 'Fechadura / Maçanetas / Trancas em geral',
    'veiculos_leves_limpador': 'Limpador em funcionamento / palhetas em bom estado',
    'veiculos_leves_ruido_interno': 'Nível de ruído interno dentro da normalidade',
    'veiculos_leves_ruido_externo': 'Nível de ruído externo dentro da normalidade',
    'veiculos_leves_painel': 'Indicações de anomalia no painel (injeção, óleo, airbag...)',
    'veiculos_leves_quebra_sol': 'Quebra-sol',
    'veiculos_leves_vidro': 'Vidro elétrico / Travas',
    'veiculos_leves_bateria': 'Bateria em bom estado',
    'veiculos_leves_suspencao': 'Suspensão / alinhamento / balanceamento',
    'van_interdicao': 'Ausência de vazamento de óleo',
    'van_cinto': 'Cinto de segurança para todos os ocupantes',
    'van_doc': 'Documentação em dia',
    'van_extintor': 'Extintor válido',
    'van_freio': 'Freios em perfeitas condições',
    'van_habilitacao': 'Habilitação do condutor',
    'van_luzes': 'Luzes funcionando',
    'van_pneus': 'Pneus em bom estado',
    'van_capacidade': 'Respeitar capacidade de passageiros',
    'van_buzina': 'Buzina funcionando',
    'van_retrovisor': 'Retrovisores em bom estado',
    'van_bancos': 'Bancos em bom estado',
    'van_limpador': 'Limpador de para-brisa funcionando',
    'van_painel': 'Indicações de anomalia no painel',
    'van_bateria': 'Bateria em bom estado',
    'ambulancia_doc': 'Documentação em dia',
    'ambulancia_habilitacao': 'Habilitação do condutor',
    'ambulancia_extintor': 'Extintor válido',
    'ambulancia_freio': 'Freios em perfeitas condições',
    'ambulancia_luzes': 'Luzes funcionando (farol, seta, emergência)',
    'ambulancia_pneus': 'Pneus em bom estado',
    'ambulancia_cinto': 'Cintos de segurança',
    'ambulancia_equipamentos': 'Equipamentos de socorro em ordem',
    'ambulancia_oxigenio': 'Cilindro de oxigênio cheio e válido',
    'ambulancia_maca': 'Macá em bom estado',
    'ambulancia_buzina': 'Buzina e sirene funcionando',
    'ambulancia_retrovisor': 'Retrovisores em bom estado',
    'ambulancia_limpador': 'Limpador funcionando',
    'ambulancia_painel': 'Indicações de anomalia no painel',
    'ambulancia_bateria': 'Bateria em bom estado',
    'onibus_doc': 'Documentação em dia',
    'onibus_habilitacao': 'Habilitação do condutor (categoria D/E)',
    'onibus_extintor': 'Extintores válidos (quantidade adequada)',
    'onibus_freio': 'Freios em perfeitas condições',
    'onibus_luzes': 'Luzes funcionando',
    'onibus_pneus': 'Pneus em bom estado',
    'onibus_cintos': 'Cintos de segurança para todos os assentos',
    'onibus_saidas': 'Saídas de emergência desobstruídas',
    'onibus_macanetas': 'Maçanetas de emergência funcionando',
    'onibus_capacidade': 'Respeitar capacidade máxima de passageiros',
    'onibus_buzina': 'Buzina funcionando',
    'onibus_retrovisor': 'Retrovisores em bom estado',
    'onibus_limpador': 'Limpador de para-brisa',
    'onibus_ar': 'Ar condicionado / ventilação',
    'onibus_bancos': 'Bancos em bom estado',
    'onibus_painel': 'Indicações de anomalia',
    'caminhao_cabinado_doc': 'Documentação em dia (CIV, seguro, RNTRC)',
    'caminhao_cabinado_habilitacao': 'Habilitação do condutor (categoria E)',
    'caminhao_cabinado_extintor': 'Extintor válido',
    'caminhao_cabinado_freio': 'Freios em perfeitas condições',
    'caminhao_cabinado_freio_motor': 'Freio motor funcionando',
    'caminhao_cabinado_luzes': 'Luzes funcionando (farol, ré, setas, freio, placa)',
    'caminhao_cabinado_pneus': 'Pneus / estepe em bom estado',
    'caminhao_cabinado_cinto': 'Cinto de segurança',
    'caminhao_cabinado_triangulo': 'Triângulo / Macaco / Chave de roda',
    'caminhao_cabinado_vazamento': 'Ausência de vazamentos (óleo, ar, combustível)',
    'caminhao_cabinado_ar_comprimido': 'Sistema de ar comprimido aprovado',
    'caminhao_cabinado_reboque': 'Acoplamento reboque aprovado',
    'caminhao_cabinado_sinal_sonoro': 'Sinal sonoro de ré',
    'caminhao_cabinado_buzina': 'Buzina',
    'caminhao_cabinado_retrovisor': 'Retrovisores em bom estado',
    'caminhao_cabinado_limpador': 'Limpador de para-brisa',
    'caminhao_cabinado_bancos': 'Bancos / estofamento',
    'caminhao_cabinado_painel': 'Indicações de anomalia no painel',
    'caminhao_cabinado_suspencao': 'Suspensão em geral',
    'caminhao_munk_doc': 'Documentação em dia',
    'caminhao_munk_habilitacao': 'Habilitação do condutor',
    'caminhao_munk_extintor': 'Extintor válido',
    'caminhao_munk_freio': 'Freios em perfeitas condições',
    'caminhao_munk_luzes': 'Luzes funcionando',
    'caminhao_munk_pneus': 'Pneus em bom estado',
    'caminhao_munk_cinto': 'Cinto de segurança',
    'caminhao_munk_vazamento': 'Ausência de vazamentos',
    'caminhao_munk_munk': 'Sistema Munk (guindaste) aprovado',
    'caminhao_munk_estabilizador': 'Estabilizadores aprovado',
    'caminhao_munk_cabo': 'Cabos de aço em bom estado',
    'caminhao_munk_sinal_sonoro': 'Sinal sonoro de ré',
    'caminhao_munk_buzina': 'Buzina',
    'caminhao_munk_retrovisor': 'Retrovisores',
    'caminhao_munk_painel': 'Indicações de anomalia',
    'caminhao_comboio_doc': 'Documentação em dia',
    'caminhao_comboio_habilitacao': 'Habilitação do condutor',
    'caminhao_comboio_extintor': 'Extintor válido',
    'caminhao_comboio_freio': 'Freios em perfeitas condições',
    'caminhao_comboio_luzes': 'Luzes funcionando',
    'caminhao_comboio_pneus': 'Pneus em bom estado',
    'caminhao_comboio_cinto': 'Cinto de segurança',
    'caminhao_comboio_vazamento': 'Ausência de vazamentos',
    'caminhao_comboio_capacidade': 'Respeitar capacidade de carga/passageiros',
    'caminhao_comboio_sinal_sonoro': 'Sinal sonoro de ré',
    'caminhao_comboio_buzina': 'Buzina',
    'caminhao_comboio_retrovisor': 'Retrovisores',
    'caminhao_comboio_painel': 'Indicações de anomalia',
    'caminhao_pipa_doc': 'Documentação em dia',
    'caminhao_pipa_habilitacao': 'Habilitação do condutor',
    'caminhao_pipa_extintor': 'Extintor válido',
    'caminhao_pipa_freio': 'Freios em perfeitas condições',
    'caminhao_pipa_luzes': 'Luzes funcionando',
    'caminhao_pipa_pneus': 'Pneus em bom estado',
    'caminhao_pipa_cinto': 'Cinto de segurança',
    'caminhao_pipa_vazamento': 'Ausência de vazamentos',
    'caminhao_pipa_tanque': 'Tanque / reservatório aprovado',
    'caminhao_pipa_valvulas': 'Válvulas e registros funcionando',
    'caminhao_pipa_sinal_sonoro': 'Sinal sonoro de ré',
    'caminhao_pipa_buzina': 'Buzina',
    'caminhao_pipa_retrovisor': 'Retrovisores',
    'caminhao_pipa_painel': 'Indicações de anomalia',
    'caminhao_basculante_doc': 'Documentação em dia',
    'caminhao_basculante_habilitacao': 'Habilitação do condutor',
    'caminhao_basculante_extintor': 'Extintor válido',
    'caminhao_basculante_freio': 'Freios em perfeitas condições',
    'caminhao_basculante_luzes': 'Luzes funcionando',
    'caminhao_basculante_pneus': 'Pneus em bom estado',
    'caminhao_basculante_cinto': 'Cinto de segurança',
    'caminhao_basculante_vazamento': 'Ausência de vazamentos',
    'caminhao_basculante_basculamento': 'Sistema de basculamento aprovado',
    'caminhao_basculante_caçamba': 'Caçamba em bom estado (sem fissuras)',
    'caminhao_basculante_cilindro': 'Cilindro hidráulico aprovado',
    'caminhao_basculante_sinal_sonoro': 'Sinal sonoro de ré',
    'caminhao_basculante_buzina': 'Buzina',
    'caminhao_basculante_retrovisor': 'Retrovisores',
    'caminhao_basculante_painel': 'Indicações de anomalia',
    'carreta_doc': 'Documentação em dia (CIV, RNTRC)',
    'carreta_freio': 'Freios da carreta funcionando',
    'carreta_pneus': 'Pneus em bom estado',
    'carreta_acoplamento': 'Acoplamento (trilho, quinta roda) aprovado',
    'carreta_luzes': 'Luzes funcionando (setas, freio, ré, placa)',
    'carreta_extintor': 'Extintor válido',
    'carreta_vazamento': 'Ausência de vazamentos (ar, óleo)',
    'carreta_ar_comprimido': 'Sistema de ar comprimido aprovado',
    'carreta_capacidade': 'Respeitar capacidade de carga',
    'carreta_tampa': 'Tampas laterais / lonas aprovado',
    'carreta_sinal_sonoro': 'Sinal sonoro de ré',
    'carreta_buzina': 'Buzina',
    'carreta_retrovisor': 'Retrovisores',
    'carreta_suspensao': 'Suspensão em geral',
    'serra_tico_doc': 'Documentação da ferramenta em dia',
    'serra_tico_treinamento': 'Usuário treinado',
    'serra_tico_cabo': 'Cabo de alimentação em bom estado',
    'serra_tico_aterramento': 'Aterramento aprovado',
    'serra_tico_lamine': 'Lâmina em bom estado e adequada',
    'serra_tico_protecao': 'Proteção de lâmina instalada',
    'serra_tico_interruptor': 'Interruptor de emergência funcionando',
    'serra_tico_carcaça': 'Carcaça íntegra',
    'serra_tico_vibracao': 'Nível de vibração normal',
    'serra_circular_bancada_doc': 'Documentação em dia',
    'serra_circular_bancada_treinamento': 'Usuário treinado',
    'serra_circular_bancada_cabo': 'Cabo de alimentação aprovado',
    'serra_circular_bancada_aterramento': 'Aterramento aprovado',
    'serra_circular_bancada_lamine': 'Lâmina em bom estado',
    'serra_circular_bancada_protecao': 'Proteção de lâmina e guia paralela',
    'serra_circular_bancada_mesa': 'Mesa de apoio em bom estado',
    'serra_circular_bancada_extintor': 'Extintor próximo',
    'serra_circular_bancada_limpeza': 'Área de trabalho limpa e sem obstáculos',
    'serra_circular_portatil_doc': 'Documentação em dia',
    'serra_circular_portatil_treinamento': 'Usuário treinado',
    'serra_circular_portatil_cabo': 'Cabo de alimentação aprovado',
    'serra_circular_portatil_aterramento': 'Aterramento aprovado',
    'serra_circular_portatil_lamine': 'Lâmina em bom estado',
    'serra_circular_portatil_protecao': 'Proteção de lâmina',
    'serra_circular_portatil_interruptor': 'Interruptor de emergência',
    'serra_circular_portatil_carcaça': 'Carcaça íntegra',
    'lixadeira_doc': 'Documentação em dia',
    'lixadeira_treinamento': 'Usuário treinado',
    'lixadeira_cabo': 'Cabo de alimentação aprovado',
    'lixadeira_aterramento': 'Aterramento aprovado',
    'lixadeira_disco': 'Disco/lixa em bom estado',
    'lixadeira_protecao': 'Proteção (tela) instalada',
    'lixadeira_mascara': 'Máscara/palheta disponível',
    'lixadeira_carcaça': 'Carcaça íntegra',
    'furadeira_doc': 'Documentação em dia',
    'furadeira_treinamento': 'Usuário treinado',
    'furadeira_cabo': 'Cabo de alimentação aprovado',
    'furadeira_aterramento': 'Aterramento aprovado',
    'furadeira_broca': 'Broca em bom estado e fixada',
    'furadeira_mandril': 'Mandril funcionando',
    'furadeira_carcaça': 'Carcaça íntegra',
    'furadeira_interruptor': 'Interruptor funcionando',
    'compressor_doc': 'Documentação em dia',
    'compressor_treinamento': 'Usuário treinado',
    'compressor_aterramento': 'Aterramento aprovado',
    'compressor_vazamento': 'Ausência de vazamentos de ar',
    'compressor_válvula': 'Válvula de segurança funcionando',
    'compressor_manometro': 'Manômetro funcionando',
    'compressor_niveis': 'Níveis de óleo e filtros',
    'compressor_correia': 'Correias em bom estado',
    'compressor_extintor': 'Extintor próximo',
    'compressor_ruidos': 'Nível de ruído normal',
    'solda_doc': 'Documentação em dia',
    'solda_treinamento': 'Usuário qualificado (NR-10)',
    'solda_aterramento': 'Aterramento aprovado',
    'solda_cabo': 'Cabo de alimentação aprovado',
    'solda_eletrodos': 'Eletrodos/Arames adequados',
    'solda_mascara': 'Máscara de solda em bom estado',
    'solda_luvas': 'Luvas de vaqueta',
    'solda_extintor': 'Extintor próximo',
    'solda_ventilacao': 'Ventilação adequada no local',
    'solda_fogos': 'Ausência de materiais inflamáveis próximos',
    'guindacho_doc': 'Documentação em dia (certificado de qualidade)',
    'guindacho_treinamento': 'Usuário treinado',
    'guindacho_correntes': 'Correntes em bom estado (sem trincas, desgaste)',
    'guindacho_ganchos': 'Ganchos com trava de segurança',
    'guindacho_alcatra': 'Alcatra em bom estado',
    'guindacho_capacidade': 'Capacidade de carga identificada',
    'guindacho_inspecao': 'Inspeção periódica em dia'
};

// Ícones por categoria
const CATEGORY_ICONS = {
    maquinas: '🚜',
    veiculos: '🚗',
    ferramentas: '🔧',
    infraestrutura: '🏗️',
    epi: '🦺',
    outro: '📦'
};