// ============================================
// DADOS DOS CHECKLISTS - NRs e Itens
// ============================================

const EQUIPMENT_TYPES = {
    maquinas: [
        {
            id: 'trator_esteira',
            name: 'Trator de Esteira',
            icon: '🚜',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia (CIR, seguro, licença)', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador com treinamento e qualificação (ASO validade)', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio carregado, lacrado e dentro do prazo de validade', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança com trava-quedas', nr: 'NR-35', risk: 'high' },
                { id: 'parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'bancos', text: 'Condições dos bancos, fixação e estofamento', nr: 'NR-12', risk: 'low' },
                { id: 'retrovisores', text: 'Retrovisores interno e externos em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'escada', text: 'Escada de acesso à cabine em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'farol', text: 'Faróis funcionando (altas, baixas, lanternas)', nr: 'NR-12', risk: 'medium' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'buzina', text: 'Buzina funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'faixa_refletiva', text: 'Faixa refletiva para visualização noturna', nr: 'NR-12', risk: 'medium' },
                { id: 'freio', text: 'Freio principal em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'freio_estacionamento', text: 'Freio de estacionamento funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'esteiras', text: 'Condição das esteiras (tensionamento, desgaste, links)', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo, água e combustível adequados', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos de óleo, combustível e água', nr: 'NR-12', risk: 'high' },
                { id: 'rotacao', text: 'Rotação do motor e equipamento acima funcionando normalmente', nr: 'NR-12', risk: 'medium' },
                { id: 'alarmes', text: 'Alarmes e indicadores do painel funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'limpeza', text: 'Equipamento limpo e organizado', nr: 'NR-12', risk: 'low' },
                { id: 'placa_identificacao', text: 'Placa de identificação e capacidade de carga visível', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'trator_agricola',
            name: 'Trator Agrícola',
            icon: '🌾',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'ROPS', text: 'Dispositivo de proteção contra capotagem (ROPS)', nr: 'NR-12', risk: 'high' },
                { id: 'parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'retrovisores', text: 'Retrovisores em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'pneus', text: 'Condição dos pneus e calibragem', nr: 'NR-12', risk: 'medium' },
                { id: 'acoplamento', text: 'Sistema de acoplamento de implementos', nr: 'NR-12', risk: 'high' },
                { id: 'PTO', text: 'Eixo de potência (PTO) com proteção', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'escavadeira',
            name: 'Escavadeira Hidráulica',
            icon: '⛏️',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia (CIR, seguro)', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança com trava-quedas', nr: 'NR-35', risk: 'high' },
                { id: 'parabrisa', text: 'Condições do para-brisa e limpador', nr: 'NR-12', risk: 'medium' },
                { id: 'bancos', text: 'Condições dos bancos e fixação', nr: 'NR-12', risk: 'low' },
                { id: 'retrovisores', text: 'Retrovisores interno e externos', nr: 'NR-12', risk: 'medium' },
                { id: 'escada', text: 'Escada e corrimãos de acesso', nr: 'NR-12', risk: 'high' },
                { id: 'farol', text: 'Faróis e lanternas funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'NR-12', risk: 'high' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'freio_estacionamento', text: 'Freio de estacionamento', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo hidráulico, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos hidráulicos', nr: 'NR-12', risk: 'high' },
                { id: 'bracos', text: 'Condição dos braços e cilindros hidráulicos', nr: 'NR-12', risk: 'high' },
                { id: 'labor', text: 'Condição da lâmina/balde', nr: 'NR-12', risk: 'medium' },
                { id: 'cabo', text: 'Cabos de aço em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'limitador', text: 'Limitador de carga instalado e funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'alarmes', text: 'Alarmes e indicadores do painel', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'retroescavadeira',
            name: 'Retroescavadeira',
            icon: '🏗️',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'ROPS', text: 'Dispositivo de proteção contra capotagem (ROPS)', nr: 'NR-12', risk: 'high' },
                { id: 'farol', text: 'Faróis e lanternas', nr: 'NR-12', risk: 'medium' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo, água e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'hidraulico', text: 'Sistema hidráulico em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'pneus', text: 'Condição dos pneus', nr: 'NR-12', risk: 'medium' },
                { id: 'pá', text: 'Condição da pá (dentes, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'garfo', text: 'Condição do garfo (se aplicável)', nr: 'NR-12', risk: 'medium' },
                { id: 'alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'rolo',
            name: 'Rolo Compactador',
            icon: '⚙️',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador com treinamento e qualificação', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'freio', text: 'Freios funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'vibracao', text: 'Sistema de vibração funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'rolos', text: 'Condição dos rolos (superfície, bordas)', nr: 'NR-12', risk: 'medium' },
                { id: 'alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'gerador',
            name: 'Gerador',
            icon: '⚡',
            nr: 'NR-10',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia', nr: 'NR-10', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado para operação', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Sistema de aterramento elétrico aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'disjuntor', text: 'Disjuntor geral funcionando', nr: 'NR-10', risk: 'high' },
                { id: 'cabinado', text: 'Parte elétrica cabineada e trancada', nr: 'NR-10', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio válido', nr: 'NR-23', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-10', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos de combustível', nr: 'NR-10', risk: 'high' },
                { id: 'ventilacao', text: 'Ventilação e resfriamento adequados', nr: 'NR-10', risk: 'medium' },
                { id: 'ruidos', text: 'Nível de ruído dentro da normalidade', nr: 'NR-10', risk: 'low' },
                { id: 'placa', text: 'Placa de identificação e dados técnicos visível', nr: 'NR-10', risk: 'medium' },
                { id: 'cabeamento', text: 'Cabeamento elétrico em bom estado', nr: 'NR-10', risk: 'high' },
            ]
        },
        {
            id: 'betoneira',
            name: 'Betoneira Elétrica',
            icon: '🪣',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação do equipamento em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador treinado', nr: 'NR-12', risk: 'high' },
                { id: 'aterramento', text: 'Cabeamento de terra aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação em bom estado', nr: 'NR-10', risk: 'high' },
                { id: 'extintor', text: 'Extintor de incêndio próximo', nr: 'NR-23', risk: 'high' },
                { id: 'tambor', text: 'Tambor limpo e em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'pá', text: 'Pá de amassar em bom estado', nr: 'NR-12', risk: 'low' },
                { id: 'rolamento', text: 'Rolamentos e engrenagens protegidos', nr: 'NR-12', risk: 'high' },
                { id: 'tela', text: 'Tela de proteção instalada', nr: 'NR-12', risk: 'high' },
                { id: 'chassi', text: 'Chassi e estrutura sem fissuras', nr: 'NR-12', risk: 'medium' },
                { id: 'interrupcao', text: 'Dispositivo de emergência funcionando', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'embarcacao',
            name: 'Embarcação',
            icon: '🚢',
            nr: 'NR-30',
            items: [
                { id: 'doc', text: 'Documentação da embarcação em dia', nr: 'NR-30', risk: 'high' },
                { id: 'tripulacao', text: 'Tripulação qualificada e documentada', nr: 'NR-30', risk: 'high' },
                { id: 'coletes', text: 'Coletes salva-vidas para todos os ocupantes', nr: 'NR-30', risk: 'high' },
                { id: 'extintor', text: 'Extintores de incêndio válidos', nr: 'NR-23', risk: 'high' },
                { id: 'botes', text: 'Botes salva-vidas em bom estado', nr: 'NR-30', risk: 'high' },
                { id: 'sinalizacao', text: 'Sinalização de socorro (rádio, fogos)', nr: 'NR-30', risk: 'medium' },
                { id: 'motor', text: 'Motor em perfeitas condições', nr: 'NR-30', risk: 'high' },
                { id: 'combustivel', text: 'Nível de combustível adequado', nr: 'NR-30', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-30', risk: 'high' },
                { id: 'casco', text: 'Condição do casco (sem fissuras, sem vazamentos)', nr: 'NR-30', risk: 'high' },
                { id: 'equipamentos', text: 'Equipamentos de navegação funcionando', nr: 'NR-30', risk: 'medium' },
                { id: 'limpeza', text: 'Embarcação limpa e organizada', nr: 'NR-30', risk: 'low' },
            ]
        },
        {
            id: 'minicarregadeira',
            name: 'Minicarregadeira',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'freio', text: 'Freios funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'garfo', text: 'Condição dos garfos', nr: 'NR-12', risk: 'medium' },
                { id: 'estabilidade', text: 'Sistema de estabilidade aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'bomba',
            name: 'Bomba Estacionária',
            icon: '💧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'tubulacoes', text: 'Tubulações e conexões em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'valvulas', text: 'Válvulas funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'mancal', text: 'Mancal e selagem em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'vibracao', text: 'Nível de vibração dentro da normalidade', nr: 'NR-12', risk: 'medium' },
                { id: 'ruidos', text: 'Nível de ruído normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'motoniveladora',
            name: 'Motoniveladora',
            icon: '🚜',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'lamina', text: 'Condição da lâmina (garras, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'articulacao', text: 'Articulação da lâmina aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'pcarregadeira',
            name: 'Pá Carregadeira',
            icon: '🚛',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'NR-35', risk: 'high' },
                { id: 'ROPS', text: 'ROPS/FOPS instalado', nr: 'NR-12', risk: 'high' },
                { id: 'farol', text: 'Faróis funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'balde', text: 'Condição do balde (dentes, lâmina)', nr: 'NR-12', risk: 'medium' },
                { id: 'suspencao', text: 'Suspensão em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'alarmes', text: 'Alarmes e indicadores', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'plataforma',
            name: 'Plataforma Elevatória',
            icon: '🪜',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia (CIR, seguro)', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado e certificado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'cinto', text: 'Trava-quedas e cinto para todos os ocupantes', nr: 'NR-35', risk: 'high' },
                { id: 'plataforma', text: 'Plataforma de trabalho íntegra', nr: 'NR-12', risk: 'high' },
                { id: 'guarda_corpo', text: 'Guarda-corpo e rodapé instalados', nr: 'NR-12', risk: 'high' },
                { id: 'escada', text: 'Escada de acesso aprovado', nr: 'NR-12', risk: 'medium' },
                { id: 'hidraulico', text: 'Sistema hidráulico sem vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'freio', text: 'Freios e trava funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis hidráulicos', nr: 'NR-12', risk: 'medium' },
                { id: 'limitador', text: 'Limitador de carga e altura aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'alarmes', text: 'Alarmes de inclinação e carga', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'sondagem',
            name: 'Equipamento de Sondagem',
            icon: '🔩',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Operador qualificado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high' },
                { id: 'estabilidade', text: 'Sistema de estabilidade aprovado', nr: 'NR-12', risk: 'high' },
                { id: 'torre', text: 'Torre de sondagem íntegra', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabos de aço em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'freio', text: 'Freios de emergência funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'niveis', text: 'Níveis de óleo e combustível', nr: 'NR-12', risk: 'medium' },
                { id: 'vazamentos', text: 'Ausência de vazamentos', nr: 'NR-12', risk: 'high' },
                { id: 'protecao', text: 'Proteções e guarda-corpos instalados', nr: 'NR-12', risk: 'high' },
            ]
        },
    ],
    veiculos: [
        {
            id: 'veiculos_leves',
            name: 'Veículos Leves',
            icon: '🚗',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'interdicao', text: 'Ausência de vazamento de óleo', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento_agua', text: 'Ausência de vazamento de água', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'doc_ipva', text: 'Documentação em dia (IPVA, licenciamento)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor de incêndio carregado, lacrado e dentro do prazo', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio_estac', text: 'Freio de estacionamento funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio_pe', text: 'Freios de pé em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando (farol, ré, setas, freio, interna, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'triangulo', text: 'Triângulo / Macaco / Chave de roda', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'velocimetro', text: 'Velocímetro / marcador de combustível / temperatura funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus / estepe / parafusos das rodas em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ar', text: 'Ar condicionado funcionando', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'parabrisa', text: 'Condições do para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Condições do retrovisor interno e externo', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'bancos', text: 'Condições dos bancos / fixação / estofamento', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'fechadura', text: 'Fechadura / Maçanetas / Trancas em geral', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'limpador', text: 'Limpador em funcionamento / palhetas em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ruido_interno', text: 'Nível de ruído interno dentro da normalidade', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'ruido_externo', text: 'Nível de ruído externo dentro da normalidade', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia no painel (injeção, óleo, airbag...)', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'quebra_sol', text: 'Quebra-sol', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'vidro', text: 'Vidro elétrico / Travas', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'suspencao', text: 'Suspensão / alinhamento / balanceamento', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'van',
            name: 'Van',
            icon: '🚐',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'interdicao', text: 'Ausência de vazamento de óleo', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança para todos os ocupantes', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'capacidade', text: 'Respeitar capacidade de passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'bancos', text: 'Bancos em bom estado', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'limpador', text: 'Limpador de para-brisa funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'ambulancia',
            name: 'Ambulância',
            icon: '🚑',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando (farol, seta, emergência)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cintos de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'equipamentos', text: 'Equipamentos de socorro em ordem', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'oxigenio', text: 'Cilindro de oxigênio cheio e válido', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'maca', text: 'Macá em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina e sirene funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'limpador', text: 'Limpador funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'bateria', text: 'Bateria em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'onibus',
            name: 'Ônibus',
            icon: '🚌',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor (categoria D/E)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintores válidos (quantidade adequada)', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cintos', text: 'Cintos de segurança para todos os assentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'saidas', text: 'Saídas de emergência desobstruídas', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'macanetas', text: 'Maçanetas de emergência funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'capacidade', text: 'Respeitar capacidade máxima de passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'buzina', text: 'Buzina funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'limpador', text: 'Limpador de para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'ar', text: 'Ar condicionado / ventilação', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'bancos', text: 'Bancos em bom estado', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_cabinado',
            name: 'Caminhão Cabinado',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia (CIV, seguro, RNTRC)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor (categoria E)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio_motor', text: 'Freio motor funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando (farol, ré, setas, freio, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus / estepe em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'triangulo', text: 'Triângulo / Macaco / Chave de roda', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos (óleo, ar, combustível)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ar_comprimido', text: 'Sistema de ar comprimido aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'reboque', text: 'Acoplamento reboque aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores em bom estado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'limpador', text: 'Limpador de para-brisa', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'bancos', text: 'Bancos / estofamento', nr: 'CIR/CONTRAN', risk: 'low', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia no painel', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
                { id: 'suspencao', text: 'Suspensão em geral', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_munk',
            name: 'Caminhão Munk',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'munk', text: 'Sistema Munk (guindaste) aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'estabilizador', text: 'Estabilizadores aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cabo', text: 'Cabos de aço em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_comboio',
            name: 'Caminhão Comboio',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'capacidade', text: 'Respeitar capacidade de carga/passageiros', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_pipa',
            name: 'Caminhão Pipa',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'tanque', text: 'Tanque / reservatório aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'valvulas', text: 'Válvulas e registros funcionando', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'caminhao_basculante',
            name: 'Caminhão Basculante',
            icon: '🚛',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'habilitacao', text: 'Habilitação do condutor', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios em perfeitas condições', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'cinto', text: 'Cinto de segurança', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'basculamento', text: 'Sistema de basculamento aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'caçamba', text: 'Caçamba em bom estado (sem fissuras)', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'cilindro', text: 'Cilindro hidráulico aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'painel', text: 'Indicações de anomalia', nr: 'CIR/CONTRAN', risk: 'high', section: 'CORREÇÃO' },
            ]
        },
        {
            id: 'carreta',
            name: 'Carreta',
            icon: '🚚',
            nr: 'CIR/CONTRAN',
            items: [
                { id: 'doc', text: 'Documentação em dia (CIV, RNTRC)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'freio', text: 'Freios da carreta funcionando', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'pneus', text: 'Pneus em bom estado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'acoplamento', text: 'Acoplamento (trilho, quinta roda) aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'luzes', text: 'Luzes funcionando (setas, freio, ré, placa)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'extintor', text: 'Extintor válido', nr: 'NR-23', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'vazamento', text: 'Ausência de vazamentos (ar, óleo)', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'ar_comprimido', text: 'Sistema de ar comprimido aprovado', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'capacidade', text: 'Respeitar capacidade de carga', nr: 'CIR/CONTRAN', risk: 'high', section: 'INTERDIÇÃO' },
                { id: 'tampa', text: 'Tampas laterais / lonas aprovado', nr: 'CIR/CONTRAN', risk: 'medium', section: 'INTERDIÇÃO' },
                { id: 'sinal_sonoro', text: 'Sinal sonoro de ré', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'buzina', text: 'Buzina', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'retrovisor', text: 'Retrovisores', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
                { id: 'suspensao', text: 'Suspensão em geral', nr: 'CIR/CONTRAN', risk: 'medium', section: 'CORREÇÃO' },
            ]
        },
    ],
    ferramentas: [
        {
            id: 'serra_tico',
            name: 'Serra Tico-Tico',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação da ferramenta em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação em bom estado', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'lamine', text: 'Lâmina em bom estado e adequada', nr: 'NR-12', risk: 'medium' },
                { id: 'protecao', text: 'Proteção de lâmina instalada', nr: 'NR-12', risk: 'high' },
                { id: 'interruptor', text: 'Interruptor de emergência funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
                { id: 'vibracao', text: 'Nível de vibração normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'serra_circular_bancada',
            name: 'Serra Circular de Bancada',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'lamine', text: 'Lâmina em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'protecao', text: 'Proteção de lâmina e guia paralela', nr: 'NR-12', risk: 'high' },
                { id: 'mesa', text: 'Mesa de apoio em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'limpeza', text: 'Área de trabalho limpa e sem obstáculos', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'serra_circular_portatil',
            name: 'Serra Circular Portátil',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'lamine', text: 'Lâmina em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'protecao', text: 'Proteção de lâmina', nr: 'NR-12', risk: 'high' },
                { id: 'interruptor', text: 'Interruptor de emergência', nr: 'NR-12', risk: 'high' },
                { id: 'carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'lixadeira',
            name: 'Lixadeira Elétrica',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'disco', text: 'Disco/lixa em bom estado', nr: 'NR-12', risk: 'medium' },
                { id: 'protecao', text: 'Proteção (tela) instalada', nr: 'NR-12', risk: 'high' },
                { id: 'mascara', text: 'Máscara/palheta disponível', nr: 'NR-6', risk: 'high' },
                { id: 'carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
            ]
        },
        {
            id: 'furadeira',
            name: 'Furadeira Elétrica',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'broca', text: 'Broca em bom estado e fixada', nr: 'NR-12', risk: 'medium' },
                { id: 'mandril', text: 'Mandril funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'carcaça', text: 'Carcaça íntegra', nr: 'NR-12', risk: 'medium' },
                { id: 'interruptor', text: 'Interruptor funcionando', nr: 'NR-12', risk: 'high' },
            ]
        },
        {
            id: 'compressor',
            name: 'Compressor de Ar',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'vazamento', text: 'Ausência de vazamentos de ar', nr: 'NR-12', risk: 'high' },
                { id: 'válvula', text: 'Válvula de segurança funcionando', nr: 'NR-12', risk: 'high' },
                { id: 'manometro', text: 'Manômetro funcionando', nr: 'NR-12', risk: 'medium' },
                { id: 'niveis', text: 'Níveis de óleo e filtros', nr: 'NR-12', risk: 'medium' },
                { id: 'correia', text: 'Correias em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'ruidos', text: 'Nível de ruído normal', nr: 'NR-12', risk: 'low' },
            ]
        },
        {
            id: 'solda',
            name: 'Máquina de Solda',
            icon: '🔧',
            nr: 'NR-10',
            items: [
                { id: 'doc', text: 'Documentação em dia', nr: 'NR-10', risk: 'high' },
                { id: 'treinamento', text: 'Usuário qualificado (NR-10)', nr: 'NR-10', risk: 'high' },
                { id: 'aterramento', text: 'Aterramento aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'cabo', text: 'Cabo de alimentação aprovado', nr: 'NR-10', risk: 'high' },
                { id: 'eletrodos', text: 'Eletrodos/Arames adequados', nr: 'NR-10', risk: 'medium' },
                { id: 'mascara', text: 'Máscara de solda em bom estado', nr: 'NR-6', risk: 'high' },
                { id: 'luvas', text: 'Luvas de vaqueta', nr: 'NR-6', risk: 'high' },
                { id: 'extintor', text: 'Extintor próximo', nr: 'NR-23', risk: 'high' },
                { id: 'ventilacao', text: 'Ventilação adequada no local', nr: 'NR-15', risk: 'high' },
                { id: 'fogos', text: 'Ausência de materiais inflamáveis próximos', nr: 'NR-23', risk: 'high' },
            ]
        },
        {
            id: 'guindacho',
            name: 'Acessório de Guindacho',
            icon: '🔧',
            nr: 'NR-12',
            items: [
                { id: 'doc', text: 'Documentação em dia (certificado de qualidade)', nr: 'NR-12', risk: 'high' },
                { id: 'treinamento', text: 'Usuário treinado', nr: 'NR-12', risk: 'high' },
                { id: 'correntes', text: 'Correntes em bom estado (sem trincas, desgaste)', nr: 'NR-12', risk: 'high' },
                { id: 'ganchos', text: 'Ganchos com trava de segurança', nr: 'NR-12', risk: 'high' },
                { id: 'alcatra', text: 'Alcatra em bom estado', nr: 'NR-12', risk: 'high' },
                { id: 'capacidade', text: 'Capacidade de carga identificada', nr: 'NR-12', risk: 'high' },
                { id: 'inspecao', text: 'Inspeção periódica em dia', nr: 'NR-12', risk: 'high' },
            ]
        },
    ]
};

// Mapeamento de IDs para nomes amigáveis
const ITEM_NAMES = {
    doc: 'Documentação',
    treinamento: 'Treinamento/Qualificação',
    extintor: 'Extintor de Incêndio',
    cinto: 'Cinto de Segurança',
    parabrisa: 'Para-brisa/Limpador',
    bancos: 'Bancos/Estofamento',
    retrovisores: 'Retrovisores',
    escada: 'Escada de Acesso',
    farol: 'Faróis/Lanternas',
    sinal_sonoro: 'Sinal Sonoro de Ré',
    buzina: 'Buzina',
    faixa_refletiva: 'Faixa Refletiva',
    freio: 'Freio Principal',
    freio_estacionamento: 'Freio de Estacionamento',
    esteiras: 'Condição das Esteiras',
    niveis: 'Níveis (Óleo/Água/Combustível)',
    vazamentos: 'Ausência de Vazamentos',
    rotacao: 'Rotação do Motor',
    alarmes: 'Alarmes/Indicadores',
    limpeza: 'Limpeza/Organização',
    placa_identificacao: 'Placa de Identificação',
    ROPS: 'Dispositivo Anti-Capotagem (ROPS)',
    pneus: 'Pneus/Parafusos',
    acoplamento: 'Sistema de Acoplamento',
    PTO: 'Eixo de Potência (PTO)',
    aterramento: 'Aterramento Elétrico',
    disjuntor: 'Disjuntor Geral',
    cabinado: 'Parte Elétrica Cabineada',
    ventilacao: 'Ventilação/Resfriamento',
    ruidos: 'Nível de Ruído',
    cabeamento: 'Cabeamento Elétrico',
    tambor: 'Tambor',
    pá: 'Pá/Lâmina',
    rolamento: 'Rolamentos/Engrenagens',
    tela: 'Tela de Proteção',
    chassi: 'Chassi/Estrutura',
    interrupcao: 'Dispositivo de Emergência',
    tripulacao: 'Tripulação Qualificada',
    coletes: 'Coletes Salva-Vidas',
    botes: 'Botes Salva-Vidas',
    sinalizacao: 'Sinalização de Socorro',
    motor: 'Motor',
    combustivel: 'Nível de Combustível',
    casco: 'Casco da Embarcação',
    equipamentos: 'Equipamentos',
    garfo: 'Garfos',
    estabilidade: 'Sistema de Estabilidade',
    lamina: 'Lâmina',
    articulacao: 'Articulação',
    suspensao: 'Suspensão',
    vazamento_agua: 'Vazamento de Água',
    doc_ipva: 'Documentação/IPVA',
    habilitacao: 'Habilitação do Condutor',
    triangulo: 'Triângulo/Macaco/Chave',
    velocimetro: 'Velocímetro/Combustível/Temperatura',
    ar: 'Ar Condicionado',
    fechadura: 'Fechaduras/Maçanetas',
    limpador: 'Limpador de Para-Brisa',
    ruido_interno: 'Ruído Interno',
    ruido_externo: 'Ruído Externo',
    painel: 'Indicações no Painel',
    quebra_sol: 'Quebra-Sol',
    vidro: 'Vidro Elétrico/Travas',
    bateria: 'Bateria',
    freio_motor: 'Freio Motor',
    ar_comprimido: 'Ar Comprimido',
    reboque: 'Acoplamento Reboque',
    tanque: 'Tanque/Reservatório',
    valvulas: 'Válvulas/Registros',
    basculamento: 'Sistema de Basculamento',
    caçamba: 'Caçamba',
    cilindro: 'Cilindro Hidráulico',
    tampa: 'Tampas/Lonas',
    munk: 'Sistema Munk',
    estabilizador: 'Estabilizadores',
    cabo: 'Cabos de Aço',
    capacidade: 'Capacidade de Carga/Passageiros',
    interdicao: 'Vazamento de Óleo',
    lamine: 'Lâmina/Disco',
    protecao: 'Proteções',
    carcaça: 'Carcaça Íntegra',
    vibracao: 'Nível de Vibração',
    mesa: 'Mesa de Apoio',
    disco: 'Disco/Lixa',
    mascara: 'Máscara/Palheta',
    broca: 'Broca',
    mandril: 'Mandril',
    válvula: 'Válvula de Segurança',
    manometro: 'Manômetro',
    correia: 'Correias',
    eletrodos: 'Eletrodos/Arames',
    luvas: 'Luvas de Vaqueta',
    fogos: 'Materiais Inflamáveis',
    correntes: 'Correntes',
    ganchos: 'Ganchos',
    alcatra: 'Alcatra',
    inspecao: 'Inspeção Periódica',
    oxigenio: 'Cilindro de Oxigênio',
    maca: 'Macá',
    saidas: 'Saídas de Emergência',
    macanetas: 'Maçanetas de Emergência',
    cintos: 'Cintos de Segurança',
    ar: 'Ar Condicionado/Ventilação',
    munk: 'Sistema Munk',
    tanque: 'Tanque/Reservatório',
    valvulas: 'Válvulas/Registros',
};

// Ícones por categoria
const CATEGORY_ICONS = {
    maquinas: '🚜',
    veiculos: '🚗',
    ferramentas: '🔧',
    infraestrutura: '🏗️',
    epi: '🦺',
    outro: '📦'
};